### ISSUE TITLE
"Cannot set property 'props' of undefined" on styled Typescript class component

### ISSUE THREAD

**Issue by emandres** [pluralsight/react-styleable#12]
See http://github.com/emandres/ts-react-styleable-repro for a reproduction of the error. It appears that this only affects class components, not function/stateless components.

**Comment by jaketrent** [comment]
@emandres I tried to repro

clone
npm install
npm run build
npm start
open localhost:8080

I saw no error in the build step or in the console in-browser.  Is there something else I need to do to expose the error?

**Comment by emandres** [comment]
D'oh, committed it with the wrong line commented. Pull again.

**Comment by jaketrent** [comment]
Got the error now.  Investigating...

**Comment by jaketrent** [comment]
@emandres Should be fixed now.  Upgraded your repo to react-styleable@3.0.1, and it was good.  Root cause was that your class-style component was seen as a function w/in styleable, and there wasn't a good reason for the distinction anyway.  See commit for more deets https://github.com/pluralsight/react-styleable/commit/56d4da90d839e0135a3a1ba1c01c51cdb378e7cd  

Thanks for the report!

**Comment by jaketrent** [comment]
Fix in v3.0.1
